Traceback (most recent call last):
  File "augmented_training.py", line 7, in <module>
    from dataset.gtsrb.train import GtsrbModel
ImportError: No module named dataset.gtsrb.train
Traceback (most recent call last):
  File "adversarial_attack.py", line 7, in <module>
    from dataset.gtsrb.train import GtsrbModel
ImportError: No module named dataset.gtsrb.train
